### ISSUE TITLE
cueball crash: TypeError: Cannot call method 'once' of undefined

### ISSUE THREAD

**Issue by davepacheco** [joyent/node-cueball#55] opened 2016-11-29 19:18 UTC
I ran a Marlin job in staging, which was probably pretty idle before this, and two of the three agents immediately crashed:

```
[2016-11-29T19:11:56.946Z] FATAL: MarlinAgent/ZoneServer/61092 on RA10141: FATAL ERROR handling request (req_id=b2339330-b667-11e6-b7fd-694db706cffa, zone=42c46fda-83b1-477c-b55b-ab890d627eb9)
    GET /dap/jobs/e9b847f9-6286-cd17-c5e8-f311cbac12b4/stor/dap/stor/cmd/cmd/auditreduce/time.c.0.0f0983fa-e9a8-419a-8e14-f3f3e020cf7a HTTP/1.1
    user-agent: restify/2.3.5 (ia32-sunos; v8/3.14.5.11; OpenSSL/1.0.1u) node/0.10.48
    accept-version: *
    date: Tue, 29 Nov 2016 19:11:56 GMT
    host: localhost
    connection: close
    --
    HTTP/1.1 200 OK
    --
    TypeError: Cannot call method 'once' of undefined
        at /opt/smartdc/agents/lib/node_modules/marlin/node_modules/cueball/lib/agent.js:212:10
        at /opt/smartdc/agents/lib/node_modules/marlin/node_modules/cueball/lib/pool.js:647:4
        at ConnectionFSM.<anonymous> (/opt/smartdc/agents/lib/node_modules/marlin/node_modules/cueball/lib/connection-fsm.js:162:4)
        at ConnectionFSM.g (events.js:180:16)
        at ConnectionFSM.emit (events.js:117:20)
        at /opt/smartdc/agents/lib/node_modules/marlin/node_modules/cueball/node_modules/mooremachine/lib/fsm.js:292:10
        at Array.forEach (native)
        at Object._onImmediate (/opt/smartdc/agents/lib/node_modules/marlin/node_modules/cueball/node_modules/mooremachine/lib/fsm.js:291:7)
        at processImmediate [as _immediateCallback] (timers.js:363:15)
```

This was cueball 1.1.4 using Node v0.10.48.

Unfortunately, restify's domain handling caught the error, so we don't have the stack context in the core file.

**Comment by arekinath** [comment] 2017-01-10 21:38
dupe of #52

**Closed by arekinath** 2017-01-10 21:38 UTC
